export const RECIPES = [
  {
    id: 1,
    title: 'Arroz de Atum',
    image: 'https://i.ibb.co/yYY8Gnk/image-4.png',
    cal: '300',
    duration: '45',
    proteins: '25',
    fats: '10',
    carbs: '15',
    ingredients: [
      '4 latas de atum em óleo',
      '500ml caldo aromático',
      '400g espinafres congelados',
      '350g arroz',
      '200g tomate pelado',
      '120g cebola',
      '120g alho francês',
      '30g alho',
      '30g salsa',
      'Raspa e sumo de 1 limão',
    ],
    preparation: [
      'Ferva 600 ml de água com as cascas da cebola, alho e alho francês.',
      'Numa panela, refogue a cebola picada, o alho, o tomate e o alho francês.',
      'Adicione o caldo aromático, a raspa e o sumo de limão, e deixe cozinhar em lume brando.',
    ],
  },
  {
    id: 2,
    title: 'Cookie americano',
    image: 'https://i.ibb.co/yYY8Gnk/image-4.png',
    cal: '300',
    duration: '40',
    proteins: '5',
    fats: '22',
    carbs: '32',
    ingredients: [
      '1/2 xícara de chá de açúcar mascavo',
      '1/2 xícara de chá de açúcar cristal',
      '1/2 xícara de chá de manteiga',
      '1 ovo',
      '1 colher de chá de essência de baunilha',
      '1 1/2 xícara de chá de farinha de trigo',
      '1/2 colher de chá de bicarbonato de sódio',
      '1/2 colher de chá de sal',
      '1 xícara de chá de gotas de chocolate',
    ],
    preparation: [
      'Em uma tigela, misture os açúcares, a manteiga, o ovo e a essência de baunilha.',
      'Acrescente a farinha, o bicarbonato e o sal.',
      'Por último, adicione as gotas de chocolate e misture bem.',
    ],
  },
  {
    id: 3,
    title: 'Salada proteica',
    image: 'https://i.ibb.co/yYY8Gnk/image-4.png',
    cal: '400',
    duration: '20',
    proteins: '22',
    fats: '4',
    carbs: '6',
    ingredients: [
      '1 peito de frango cozido e desfiado',
      '1/2 xícara de chá de cenoura ralada',
      '1/2 xícara de chá de beterraba ralada',
      '1/2 xícara de chá de vagem cozida picada',
      '1/2 xícara de chá de milho',
      '1/2 xícara de chá de ervilha',
      '1/2 xícara de chá de maionese',
      'Sal e pimenta a gosto',
      '1/2 xícara de chá de batata palha',
    ],
    preparation: [
      'Em uma tigela, misture o frango, a cenoura, a beterraba, a vagem, o milho e a ervilha.',
      'Tempere com a maionese, o sal e a pimenta.',
      'Coloque em uma travessa e cubra com a batata palha.',
    ],
  },
  {
    id: 4,
    title: 'Strogonoff de Carne',
    image: 'https://i.ibb.co/yYY8Gnk/image-4.png',
    cal: '500',
    duration: '60',
    proteins: '32',
    fats: '20',
    carbs: '16',
    ingredients: [
      '1 kg de carne de sua preferência',
      '1 lata de creme de leite',
      '1 lata de molho de tomate',
      '1 cebola picada',
      '1 colher de sopa de mostarda',
      '1 colher de sopa de catchup',
      '1 colher de sopa de óleo',
      'Sal e pimenta a gosto',
    ],
    preparation: [
      'Em uma panela, doure a cebola no óleo.',
      'Adicione a carne e deixe cozinhar.',
      'Acrescente o molho de tomate, a mostarda, o catchup, o sal e a pimenta.',
      'Por último, adicione o creme de leite e misture bem.',
    ],
  },
]
